name: Build EXE

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: pip install pyinstaller PyQt5

    - name: Build EXE
      run: pyinstaller --onefile --windowed tor_gui.py

    - name: Upload EXE
      uses: actions/upload-artifact@v2
      with:
        name: tor_gui_exe
        path: dist/tor_gui.exe
